name: Release

on:
  push:
    tags: [ 'v*.*.*' ]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build
        run: go build -ldflags "-X main.version=${GITHUB_REF_NAME}" -o web_proxy_cache
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./web_proxy_cache
